version: "3"
services:
  saml:
    environment:
      - DJANGO_ENV
      - DJANGO_SECRET_KEY
      - SAML_KEY
      - SAML_URL
      - SITE_URL
    image: "aswwu/django-saml:${DJANGO_TAG}"
    build: .
    container_name: django_saml
    volumes:
      - "${SAML_CERTS_DIR}:/home/django/django_server/saml/certs"
    restart: on-failure
    ports:
      - "${DJANGO_PORT}:8000"
